[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/:name"
  to = "/.netlify/functions/:name"
  status = 200
  force = true

[[edge_functions]]
  path = "/api/*"
  function = "block-bots"


